### PR TITLE
Start of the structure for ldmud and mudlib containers

### PR DESCRIPTION
**Pull request by borkweb**
The `build/` directories hold the relevant `Dockerfile`s. Check out the `INSTALL.md` for info on how to build then run them. As-is, this builds and starts two containers, one for the ldmud and one for the mudlib.

~That being said, there's a bunch that isn't working because I don't entirely know how to get ldmud up and running. It seems like there are some dependencies that are missing that you can probably identify at the drop of a hat. I figure this could at least start the conversation! To see the dependency issue, do the following:~

1. ~Edit `build/ldmud/Dockerfile` and uncomment the `autogen.sh && ./configure && make`~
1. ~From the root directory, run: `docker build -t acmemud/driver:3.5.0 build/driver`~

Prerequisites: You need docker installed and running (of course)

**EDIT:** I've dropped the commands to get stuff up and running in [a comment down below](https://github.com/acmemud/ops/pull/10#issuecomment-301105342).

See: #2 & #3

### CODE REVIEW

**Comment by borkweb** [comment]
Question for you, @bobalu113:

~Does the ldmud driver need the mudlib in the `lib/` directory before the compile happens?~

Answered via EotL! LDMud compiles mudlib after the fact.

**Comment by borkweb** [comment]
ldmud is now being compiled as a part of the ldmud container. I realized I was attempting to compile it on a 64-bit ubuntu and `autogen.sh` wasn't actually functioning. I've updated the compilation steps to generate the `configure`, run it, then `make`.

The missing piece (and maybe there are more) are the commands needed to run the mud. I'm thinking a third container might make sense.

A three-container setup could be sort of like this:
- **mudlib container** - contain the mudlib source and expose a volume
- **driver container** - contain the ldmud source, compile source, and expose a volume
- **mud container** - include the volumes from mudlib and driver, expose the port, and run the mud

**Comment by borkweb** [comment]
I've gone ahead and made the third container because it makes sense. That being said, the `ldmud 2010` execution crashes and I'm unsure why. This is starting to get into more unknown territory for me. Here's the build commands and how to get it up and running:

### Building the containers

```
./build.sh
```

### Starting the containers
```
./start.sh
OR
docker-compose up -d
```

I'd suggest using something like [Kitematic](https://kitematic.com/) to view and interact with the docker containers (if working locally).

**Comment by bobalu113** [comment]
I had to do a little reconfiguration but I got this working with Acme MUD if you update your fork. I had a couple questions:
1. Why does the mudlib container use a different image? Is this because we're only using it to expose volumes? At some point I might want to also have a process running in them to manage/expose the state of the volume.
2. At some point I need to copy the driver source code into the mudlib so people can reference it from the game. Not sure what the place is for that.
3. How does setting up a development environment work? I want to be able to edit the mudlib with my favorite text editor when running locally so the filesystem needs to be exposed somehow.

I think next I need to understand how deployment works. I installed Kitematic but got some big ugly error when it tried to spin up the Docker Vbox.

**Pull request merged**
